'use strict';

/** @type {import('sequelize-cli').Migration} */
export default {
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert(
            'Turnos',
            [
                {
                    id: 1,
                    fecha: new Date(2025, 11, 9, 12 - 3, 0),
                    descripcion: 'Control',
                    especialidad: 'Traumatologia',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 2,
                },
                {
                    id: 2,
                    fecha: new Date(2025, 11, 9, 12 - 3, 30),
                    descripcion: 'Tomografia',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 2,
                },
                {
                    id: 3,
                    fecha: new Date(2025, 11, 9, 13 - 3, 0),
                    descripcion: 'Rayos X',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 2,
                },
                {
                    id: 4,
                    fecha: new Date(2025, 11, 9, 13 - 3, 30),
                    descripcion: 'Control de rutina',
                    especialidad: 'Clínica médica',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 2,
                },
                {
                    id: 5,
                    fecha: new Date(2025, 11, 9, 14 - 3, 0),
                    descripcion: 'Consulta de rutina',
                    especialidad: 'Clínica médica',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 2,
                },
                {
                    id: 6,
                    fecha: new Date(2025, 11, 9, 14 - 3, 30),
                    descripcion: 'Control cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 2,
                },
                {
                    id: 7,
                    fecha: new Date(2025, 11, 9, 15 - 3, 0),
                    descripcion: 'Estudio oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 2,
                },
                {
                    id: 8,
                    fecha: new Date(2025, 11, 9, 15 - 3, 30),
                    descripcion: 'Control urológico',
                    especialidad: 'Urología',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 2,
                },
                {
                    id: 9,
                    fecha: new Date(2025, 11, 9, 16 - 3, 0),
                    descripcion: 'Consulta dermatológica',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 9,
                    PrestadorId: 2,
                },
                {
                    id: 10,
                    fecha: new Date(2025, 11, 9, 16 - 3, 30),
                    descripcion: 'Evaluación psiquiátrica',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 10,
                    PrestadorId: 2,
                },
                {
                    id: 11,
                    fecha: new Date(2025, 11, 9, 17 - 3, 0),
                    descripcion: 'Consulta clínica',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 2,
                },
                {
                    id: 12,
                    fecha: new Date(2025, 11, 9, 17 - 3, 30),
                    descripcion: 'Control pediátrico',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 2,
                },
                {
                    id: 13,
                    fecha: new Date(2025, 11, 5, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 2,
                },
                {
                    id: 14,
                    fecha: new Date(2025, 11, 5, 8 - 3, 30),
                    descripcion: 'Control de presión',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 2,
                },
                {
                    id: 15,
                    fecha: new Date(2025, 11, 5, 9 - 3, 0),
                    descripcion: 'Análisis de laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 2,
                },
                {
                    id: 16,
                    fecha: new Date(2025, 11, 5, 9 - 3, 30),
                    descripcion: 'Evaluación oftalmológica',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 2,
                },
                {
                    id: 17,
                    fecha: new Date(2025, 11, 5, 10 - 3, 0),
                    descripcion: 'Consulta traumatológica',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 2,
                },
                {
                    id: 18,
                    fecha: new Date(2025, 11, 5, 10 - 3, 30),
                    descripcion: 'Control dermatológico',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 2,
                },
                {
                    id: 19,
                    fecha: new Date(2025, 11, 12, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 2,
                },
                {
                    id: 20,
                    fecha: new Date(2025, 11, 12, 8 - 3, 30),
                    descripcion: 'Control cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 2,
                },
                {
                    id: 21,
                    fecha: new Date(2025, 11, 12, 9 - 3, 0),
                    descripcion: 'Laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 2,
                },
                {
                    id: 22,
                    fecha: new Date(2025, 11, 12, 9 - 3, 30),
                    descripcion: 'Control pediátrico',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 2,
                },
                {
                    id: 23,
                    fecha: new Date(2025, 11, 12, 10 - 3, 0),
                    descripcion: 'Consulta traumatológica',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 2,
                },
                {
                    id: 24,
                    fecha: new Date(2025, 11, 12, 10 - 3, 30),
                    descripcion: 'Consulta dermatológica',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 2,
                },
                {
                    id: 25,
                    fecha: new Date(2025, 11, 12, 11 - 3, 0),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 2,
                },
                // --- 17 de diciembre ---
                {
                    id: 26,
                    fecha: new Date(2025, 11, 16, 8 - 3, 0),
                    descripcion: 'Consulta clínica',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 2,
                },
                {
                    id: 27,
                    fecha: new Date(2025, 11, 16, 8 - 3, 30),
                    descripcion: 'Rayos X',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 9,
                    PrestadorId: 2,
                },
                {
                    id: 28,
                    fecha: new Date(2025, 11, 16, 9 - 3, 0),
                    descripcion: 'Consulta urológica',
                    especialidad: 'Urología',
                    estado: 'Pendiente',
                    AfiliadoId: 10,
                    PrestadorId: 2,
                },
                {
                    id: 29,
                    fecha: new Date(2025, 11, 16, 9 - 3, 30),
                    descripcion: 'Evaluación psiquiátrica',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 2,
                },
                {
                    id: 30,
                    fecha: new Date(2025, 11, 16, 10 - 3, 0),
                    descripcion: 'Control dermatológico',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 2,
                },
                // --- 20 de diciembre ---
                {
                    id: 31,
                    fecha: new Date(2025, 11, 19, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 2,
                },
                {
                    id: 32,
                    fecha: new Date(2025, 11, 19, 8 - 3, 30),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 2,
                },
                {
                    id: 33,
                    fecha: new Date(2025, 11, 19, 9 - 3, 0),
                    descripcion: 'Consulta traumatológica',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 2,
                },
                {
                    id: 34,
                    fecha: new Date(2025, 11, 19, 9 - 3, 30),
                    descripcion: 'Cardiología - control',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 2,
                },
                {
                    id: 35,
                    fecha: new Date(2025, 11, 19, 10 - 3, 0),
                    descripcion: 'Evaluación psiquiátrica',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 2,
                },
                {
                    id: 36,
                    fecha: new Date(2025, 11, 19, 10 - 3, 30),
                    descripcion: 'Control pediátrico',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 2,
                },
                {
                    id: 37,
                    fecha: new Date(2025, 11, 19, 11 - 3, 0),
                    descripcion: 'Ecografía',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 2,
                },
                {
                    id: 38,
                    fecha: new Date(2025, 11, 19, 11 - 3, 30),
                    descripcion: 'Consulta dermatológica',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 2,
                },
                {
                    id: 39,
                    fecha: new Date(2025, 11, 19, 12 - 3, 0),
                    descripcion: 'Consulta clínica',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 9,
                    PrestadorId: 2,
                },
                // --- 27 de diciembre ---
                {
                    id: 40,
                    fecha: new Date(2025, 11, 26, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 10,
                    PrestadorId: 2,
                },
                {
                    id: 41,
                    fecha: new Date(2025, 11, 26, 8 - 3, 30),
                    descripcion: 'Control cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 2,
                },
                {
                    id: 42,
                    fecha: new Date(2025, 11, 26, 9 - 3, 0),
                    descripcion: 'Rayos X',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 2,
                },
                {
                    id: 43,
                    fecha: new Date(2025, 11, 26, 9 - 3, 30),
                    descripcion: 'Control dermatológico',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 2,
                },
                {
                    id: 44,
                    fecha: new Date(2025, 11, 26, 10 - 3, 0),
                    descripcion: 'Consulta traumatológica',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 2,
                },
                {
                    id: 45,
                    fecha: new Date(2025, 11, 26, 10 - 3, 30),
                    descripcion: 'Evaluación pediátrica',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 2,
                },
                // --- 4 de diciembre ---
                {
                    id: 46,
                    fecha: new Date(2025, 11, 4, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 3,
                },
                {
                    id: 47,
                    fecha: new Date(2025, 11, 4, 8 - 3, 30),
                    descripcion: 'Control cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 3,
                },
                {
                    id: 48,
                    fecha: new Date(2025, 11, 4, 9 - 3, 0),
                    descripcion: 'Consulta pediátrica',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 3,
                },
                {
                    id: 49,
                    fecha: new Date(2025, 11, 4, 9 - 3, 30),
                    descripcion: 'Laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 3,
                },
                {
                    id: 50,
                    fecha: new Date(2025, 11, 4, 10 - 3, 0),
                    descripcion: 'Control dermatológico',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 3,
                },
                {
                    id: 51,
                    fecha: new Date(2025, 11, 4, 10 - 3, 30),
                    descripcion: 'Rayos X',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 3,
                },
                {
                    id: 52,
                    fecha: new Date(2025, 11, 4, 11 - 3, 0),
                    descripcion: 'Consulta oftalmológica',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 3,
                },
                {
                    id: 53,
                    fecha: new Date(2025, 11, 4, 11 - 3, 30),
                    descripcion: 'Consulta urológica',
                    especialidad: 'Urología',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 3,
                },
                // --- 7 de diciembre ---
                {
                    id: 54,
                    fecha: new Date(2025, 11, 1, 8 - 3, 0),
                    descripcion: 'Consulta clínica',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 9,
                    PrestadorId: 3,
                },
                {
                    id: 55,
                    fecha: new Date(2025, 11, 1, 8 - 3, 30),
                    descripcion: 'Control pediátrico',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 10,
                    PrestadorId: 3,
                },
                {
                    id: 56,
                    fecha: new Date(2025, 11, 1, 9 - 3, 0),
                    descripcion: 'Estudio cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 3,
                },
                {
                    id: 57,
                    fecha: new Date(2025, 11, 1, 9 - 3, 30),
                    descripcion: 'Consulta psiquiátrica',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 3,
                },
                {
                    id: 58,
                    fecha: new Date(2025, 11, 1, 10 - 3, 0),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 3,
                },
                {
                    id: 59,
                    fecha: new Date(2025, 11, 1, 10 - 3, 30),
                    descripcion: 'Dermatología',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 3,
                },
                // --- 11 de diciembre ---
                {
                    id: 60,
                    fecha: new Date(2025, 11, 11, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 3,
                },
                {
                    id: 61,
                    fecha: new Date(2025, 11, 11, 8 - 3, 30),
                    descripcion: 'Control cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 3,
                },
                {
                    id: 62,
                    fecha: new Date(2025, 11, 11, 9 - 3, 0),
                    descripcion: 'Ecografía',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 3,
                },
                {
                    id: 63,
                    fecha: new Date(2025, 11, 11, 9 - 3, 30),
                    descripcion: 'Consulta pediátrica',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 3,
                },
                {
                    id: 64,
                    fecha: new Date(2025, 11, 11, 10 - 3, 0),
                    descripcion: 'Consulta dermatológica',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 3,
                },
                {
                    id: 65,
                    fecha: new Date(2025, 11, 11, 10 - 3, 30),
                    descripcion: 'Psiquiatría',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 3,
                },
                {
                    id: 66,
                    fecha: new Date(2025, 11, 11, 11 - 3, 0),
                    descripcion: 'Oftalmología',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 9,
                    PrestadorId: 3,
                },
                {
                    id: 67,
                    fecha: new Date(2025, 11, 11, 11 - 3, 30),
                    descripcion: 'Traumatología',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 10,
                    PrestadorId: 3,
                },
                {
                    id: 68,
                    fecha: new Date(2025, 11, 11, 12 - 3, 0),
                    descripcion: 'Laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 3,
                },
                // --- 14 de diciembre ---
                {
                    id: 69,
                    fecha: new Date(2025, 11, 8, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 3,
                },
                {
                    id: 70,
                    fecha: new Date(2025, 11, 8, 8 - 3, 30),
                    descripcion: 'Cardiología',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 3,
                },
                {
                    id: 71,
                    fecha: new Date(2025, 11, 8, 9 - 3, 0),
                    descripcion: 'Traumatología',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 3,
                },
                {
                    id: 72,
                    fecha: new Date(2025, 11, 8, 9 - 3, 30),
                    descripcion: 'Dermatología',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 3,
                },
                {
                    id: 73,
                    fecha: new Date(2025, 11, 8, 10 - 3, 0),
                    descripcion: 'Pediatría',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 3,
                },
                {
                    id: 74,
                    fecha: new Date(2025, 11, 8, 10 - 3, 30),
                    descripcion: 'Laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 3,
                },
                {
                    id: 75,
                    fecha: new Date(2025, 11, 8, 11 - 3, 0),
                    descripcion: 'Psiquiatría',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 3,
                },
                // --- 18 de diciembre ---
                {
                    id: 76,
                    fecha: new Date(2025, 11, 18, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 3,
                },
                {
                    id: 77,
                    fecha: new Date(2025, 11, 18, 8 - 3, 30),
                    descripcion: 'Control cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 3,
                },
                {
                    id: 78,
                    fecha: new Date(2025, 11, 18, 9 - 3, 0),
                    descripcion: 'Rayos X',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 9,
                    PrestadorId: 3,
                },
                {
                    id: 79,
                    fecha: new Date(2025, 11, 18, 9 - 3, 30),
                    descripcion: 'Consulta traumatológica',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 3,
                },
                {
                    id: 80,
                    fecha: new Date(2025, 11, 18, 10 - 3, 0),
                    descripcion: 'Pediatría',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 3,
                },
                {
                    id: 81,
                    fecha: new Date(2025, 11, 18, 10 - 3, 30),
                    descripcion: 'Dermatología',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 3,
                },
                {
                    id: 82,
                    fecha: new Date(2025, 11, 18, 11 - 3, 0),
                    descripcion: 'Psiquiatría',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 3,
                },
                {
                    id: 83,
                    fecha: new Date(2025, 11, 18, 11 - 3, 30),
                    descripcion: 'Oftalmología',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 3,
                },
                {
                    id: 84,
                    fecha: new Date(2025, 11, 18, 12 - 3, 0),
                    descripcion: 'Control clínico',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 3,
                },
                {
                    id: 85,
                    fecha: new Date(2025, 11, 18, 12 - 3, 30),
                    descripcion: 'Estudio complementario',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 3,
                },
                // --- 21 de diciembre ---
                {
                    id: 86,
                    fecha: new Date(2025, 11, 15, 8 - 3, 0),
                    descripcion: 'Consulta clínica',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 3,
                },
                {
                    id: 87,
                    fecha: new Date(2025, 11, 15, 8 - 3, 30),
                    descripcion: 'Laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 3,
                },
                {
                    id: 88,
                    fecha: new Date(2025, 11, 15, 9 - 3, 0),
                    descripcion: 'Control dermatológico',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 3,
                },
                {
                    id: 89,
                    fecha: new Date(2025, 11, 15, 9 - 3, 30),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 3,
                },
                {
                    id: 90,
                    fecha: new Date(2025, 11, 15, 10 - 3, 0),
                    descripcion: 'Traumatología',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 9,
                    PrestadorId: 3,
                },
                // --- 25 de diciembre ---
                {
                    id: 91,
                    fecha: new Date(2025, 11, 23, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 10,
                    PrestadorId: 3,
                },
                {
                    id: 92,
                    fecha: new Date(2025, 11, 23, 8 - 3, 30),
                    descripcion: 'Cardiología',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 3,
                },
                {
                    id: 93,
                    fecha: new Date(2025, 11, 23, 9 - 3, 0),
                    descripcion: 'Laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 3,
                },
                {
                    id: 94,
                    fecha: new Date(2025, 11, 23, 9 - 3, 30),
                    descripcion: 'Consulta pediátrica',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 3,
                },
                {
                    id: 95,
                    fecha: new Date(2025, 11, 23, 10 - 3, 0),
                    descripcion: 'Dermatología',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 3,
                },
                {
                    id: 96,
                    fecha: new Date(2025, 11, 23, 10 - 3, 30),
                    descripcion: 'Psiquiatría',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 3,
                },
                {
                    id: 97,
                    fecha: new Date(2025, 11, 23, 11 - 3, 0),
                    descripcion: 'Oftalmología',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 3,
                },
                {
                    id: 98,
                    fecha: new Date(2025, 11, 23, 11 - 3, 30),
                    descripcion: 'Traumatología',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 3,
                },
                {
                    id: 99,
                    fecha: new Date(2025, 11, 23, 12 - 3, 0),
                    descripcion: 'Cardiología - control',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 3,
                },
                {
                    id: 100,
                    fecha: new Date(2025, 11, 23, 12 - 3, 30),
                    descripcion: 'Consulta clínica',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 3,
                },
                {
                    id: 101,
                    fecha: new Date(2025, 11, 23, 13 - 3, 0),
                    descripcion: 'Ecografía',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 3,
                },
                // --- 28 de diciembre ---
                {
                    id: 102,
                    fecha: new Date(2025, 11, 22, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 9,
                    PrestadorId: 3,
                },
                {
                    id: 103,
                    fecha: new Date(2025, 11, 22, 8 - 3, 30),
                    descripcion: 'Control cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 10,
                    PrestadorId: 3,
                },
                {
                    id: 104,
                    fecha: new Date(2025, 11, 22, 9 - 3, 0),
                    descripcion: 'Rayos X',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 3,
                },
                {
                    id: 105,
                    fecha: new Date(2025, 11, 22, 9 - 3, 30),
                    descripcion: 'Dermatología',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 3,
                },
                {
                    id: 106,
                    fecha: new Date(2025, 11, 22, 10 - 3, 0),
                    descripcion: 'Traumatología',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 3,
                },
                {
                    id: 107,
                    fecha: new Date(2025, 11, 22, 10 - 3, 30),
                    descripcion: 'Pediatría',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 3,
                },
                {
                    id: 108,
                    fecha: new Date(2025, 11, 22, 11 - 3, 0),
                    descripcion: 'Consulta oftalmológica',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 3,
                },
                {
                    id: 109,
                    fecha: new Date(2025, 11, 22, 11 - 3, 30),
                    descripcion: 'Psiquiatría',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 3,
                },
                // --- 2 de diciembre ---
                {
                    id: 110,
                    fecha: new Date(2025, 11, 2, 10 - 3, 30),
                    descripcion: 'Pediatría',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 4,
                },
                {
                    id: 111,
                    fecha: new Date(2025, 11, 2, 11 - 3, 0),
                    descripcion: 'Consulta oftalmológica',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 4,
                },
                {
                    id: 112,
                    fecha: new Date(2025, 11, 2, 11 - 3, 30),
                    descripcion: 'Psiquiatría',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 4,
                },
                // --- 4 de diciembre ---
                {
                    id: 113,
                    fecha: new Date(2025, 11, 4, 9 - 3, 0),
                    descripcion: 'Estudio cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 4,
                },
                {
                    id: 114,
                    fecha: new Date(2025, 11, 4, 9 - 3, 30),
                    descripcion: 'Consulta psiquiátrica',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 4,
                },
                {
                    id: 115,
                    fecha: new Date(2025, 11, 4, 10 - 3, 0),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 4,
                },
                {
                    id: 116,
                    fecha: new Date(2025, 11, 4, 10 - 3, 30),
                    descripcion: 'Dermatología',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 4,
                },
                // --- 5 de diciembre ---
                {
                    id: 117,
                    fecha: new Date(2025, 11, 5, 8 - 3, 0),
                    descripcion: 'Consulta general',
                    especialidad: 'Clínica Médica',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 4,
                },
                {
                    id: 118,
                    fecha: new Date(2025, 11, 5, 8 - 3, 30),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 4,
                },
                {
                    id: 119,
                    fecha: new Date(2025, 11, 5, 9 - 3, 0),
                    descripcion: 'Consulta traumatológica',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 4,
                },
                {
                    id: 120,
                    fecha: new Date(2025, 11, 5, 9 - 3, 30),
                    descripcion: 'Cardiología - control',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 4,
                },
                {
                    id: 121,
                    fecha: new Date(2025, 11, 5, 10 - 3, 0),
                    descripcion: 'Evaluación psiquiátrica',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 4,
                },
                // --- 10 de diciembre ---
                {
                    id: 122,
                    fecha: new Date(2025, 11, 10, 9 - 3, 30),
                    descripcion: 'Laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 4,
                },
                {
                    id: 123,
                    fecha: new Date(2025, 11, 10, 10 - 3, 0),
                    descripcion: 'Control dermatológico',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 4,
                },
                {
                    id: 124,
                    fecha: new Date(2025, 11, 10, 10 - 3, 30),
                    descripcion: 'Rayos X',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 4,
                },
                // --- 11 de diciembre ---
                {
                    id: 125,
                    fecha: new Date(2025, 11, 11, 10 - 3, 0),
                    descripcion: 'Consulta traumatológica',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 4,
                },
                {
                    id: 126,
                    fecha: new Date(2025, 11, 11, 10 - 3, 30),
                    descripcion: 'Consulta dermatológica',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 4,
                },
                {
                    id: 127,
                    fecha: new Date(2025, 11, 11, 11 - 3, 0),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 4,
                },
                // -- 15 de diciembre
                {
                    id: 128,
                    fecha: new Date(2025, 11, 15, 9 - 3, 0),
                    descripcion: 'Análisis de laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 4,
                },
                {
                    id: 129,
                    fecha: new Date(2025, 11, 15, 9 - 3, 30),
                    descripcion: 'Evaluación oftalmológica',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 4,
                },
                {
                    id: 130,
                    fecha: new Date(2025, 11, 15, 10 - 3, 0),
                    descripcion: 'Consulta traumatológica',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 4,
                },
                {
                    id: 131,
                    fecha: new Date(2025, 11, 15, 10 - 3, 30),
                    descripcion: 'Control dermatológico',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 4,
                },
                // 17 de diciembre
                {
                    id: 132,
                    fecha: new Date(2025, 11, 17, 8 - 3, 30),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 4,
                },
                {
                    id: 133,
                    fecha: new Date(2025, 11, 17, 9 - 3, 0),
                    descripcion: 'Consulta traumatológica',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 4,
                },
                {
                    id: 134,
                    fecha: new Date(2025, 11, 17, 9 - 3, 30),
                    descripcion: 'Cardiología - control',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 4,
                },
                {
                    id: 135,
                    fecha: new Date(2025, 11, 17, 10 - 3, 0),
                    descripcion: 'Evaluación psiquiátrica',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 4,
                },
                {
                    id: 136,
                    fecha: new Date(2025, 11, 17, 10 - 3, 30),
                    descripcion: 'Control pediátrico',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 6,
                    PrestadorId: 4,
                },
                // 19 de diciembre
                {
                    id: 137,
                    fecha: new Date(2025, 11, 19, 9 - 3, 0),
                    descripcion: 'Control dermatológico',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 7,
                    PrestadorId: 4,
                },
                {
                    id: 138,
                    fecha: new Date(2025, 11, 19, 9 - 3, 30),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 8,
                    PrestadorId: 4,
                },
                {
                    id: 139,
                    fecha: new Date(2025, 11, 19, 10 - 3, 0),
                    descripcion: 'Traumatología',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 9,
                    PrestadorId: 4,
                },
                // 23 de diciembre
                {
                    id: 140,
                    fecha: new Date(2025, 11, 23, 12 - 3, 0),
                    descripcion: 'Control',
                    especialidad: 'Traumatologia',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 4,
                },
                {
                    id: 141,
                    fecha: new Date(2025, 11, 23, 12 - 3, 30),
                    descripcion: 'Tomografia',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 4,
                },
                {
                    id: 142,
                    fecha: new Date(2025, 11, 23, 13 - 3, 0),
                    descripcion: 'Rayos X',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 4,
                },
                {
                    id: 143,
                    fecha: new Date(2025, 11, 23, 13 - 3, 30),
                    descripcion: 'Control de rutina',
                    especialidad: 'Clínica médica',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 4,
                },
                // 29 de diciembre
                {
                    id: 144,
                    fecha: new Date(2025, 11, 29, 8 - 3, 30),
                    descripcion: 'Cardiología',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 4,
                },
                {
                    id: 145,
                    fecha: new Date(2025, 11, 29, 9 - 3, 0),
                    descripcion: 'Traumatología',
                    especialidad: 'Traumatología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 4,
                },
                {
                    id: 146,
                    fecha: new Date(2025, 11, 29, 9 - 3, 30),
                    descripcion: 'Dermatología',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 4,
                },
                {
                    id: 147,
                    fecha: new Date(2025, 11, 29, 10 - 3, 0),
                    descripcion: 'Pediatría',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 4,
                },
                {
                    id: 148,
                    fecha: new Date(2025, 11, 29, 10 - 3, 30),
                    descripcion: 'Laboratorio',
                    especialidad: 'Laboratorio',
                    estado: 'Pendiente',
                    AfiliadoId: 5,
                    PrestadorId: 4,
                },
                //--- 6 enero ---
                {
                    id: 149,
                    fecha: new Date(2026, 0, 6, 10 - 3, 30),
                    descripcion: 'Pediatría',
                    especialidad: 'Pediatría',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 3,
                },
                {
                    id: 150,
                    fecha: new Date(2026, 0, 6, 11 - 3, 0),
                    descripcion: 'Consulta oftalmológica',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 3,
                    PrestadorId: 3,
                },
                {
                    id: 151,
                    fecha: new Date(2026, 0, 6, 11 - 3, 30),
                    descripcion: 'Psiquiatría',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 4,
                    PrestadorId: 3,
                },
                // --- 8 de enero ---
                {
                    id: 152,
                    fecha: new Date(2026, 0, 8, 9 - 3, 0),
                    descripcion: 'Estudio cardiológico',
                    especialidad: 'Cardiología',
                    estado: 'Pendiente',
                    AfiliadoId: 11,
                    PrestadorId: 3,
                },
                {
                    id: 153,
                    fecha: new Date(2026, 0, 8, 9 - 3, 30),
                    descripcion: 'Consulta psiquiátrica',
                    especialidad: 'Psiquiatría',
                    estado: 'Pendiente',
                    AfiliadoId: 12,
                    PrestadorId: 3,
                },
                {
                    id: 154,
                    fecha: new Date(2026, 0, 8, 10 - 3, 0),
                    descripcion: 'Control oftalmológico',
                    especialidad: 'Oftalmología',
                    estado: 'Pendiente',
                    AfiliadoId: 1,
                    PrestadorId: 3,
                },
                {
                    id: 155,
                    fecha: new Date(2026, 0, 8, 10 - 3, 30),
                    descripcion: 'Dermatología',
                    especialidad: 'Dermatología',
                    estado: 'Pendiente',
                    AfiliadoId: 2,
                    PrestadorId: 3,
                },
            ],
            {}
        );
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Turnos', null, {});
    },
};
